apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-shared
  namespace: filetracker
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi